### ISSUE TITLE
Example doesn't work with futures 0.2.0

### ISSUE THREAD

**Issue by Gurpartap** [fede1024/rust-rdkafka#84]
The async processing example works on `futures 0.1.20` but fails on the latest [futures 0.2.0](https://github.com/rust-lang-nursery/futures-rs/releases/tag/0.2.0) release with the following errors:

https://github.com/fede1024/rust-rdkafka/blob/97e50a501dce114d41d4db80d6c16b9e2e986e2d/examples/asynchronous_processing.rs#L79-L101

```
error[E0599]: no method named `filter_map` found for type `rdkafka::consumer::MessageStream<'_, rdkafka::consumer::DefaultConsumerContext>` in the current scope
  --> src/main.rs:81:10
   |
81 |         .filter_map(|result| {  // Filter out errors
   |          ^^^^^^^^^^
   |
   = note: the method `filter_map` exists but the following trait bounds were not satisfied:
           `&mut rdkafka::consumer::MessageStream<'_, rdkafka::consumer::DefaultConsumerContext> : std::iter::Iterator`
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
10 | use futures::stream::Stream;
   |

error[E0599]: no method named `and_then` found for type `futures_cpupool::CpuFuture<std::string::String, _>` in the current scope
  --> src/main.rs:99:12
   |
99 |         }).and_then(move |computation_result| {
   |            ^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
10 | use futures::future::Future;
   |
```

```toml
[dependencies]
log = "0.4.1"
futures = "0.2.0"
# futures = "0.1.20" # works
futures-cpupool = "0.1.8"
rand = "0.5.0-pre.0"
tokio-core = "0.1.17"
rdkafka = "0.15.0"
```

**Comment by kaiba696** [comment]
+1

**Comment by jwilm** [comment]
The suggestions from Rust core team are to skip futures 0.2 and wait for futures 0.3.

**Comment by nbigaouette-eai** [comment]
`Future` trait is now stable! https://blog.rust-lang.org/2019/07/04/Rust-1.36.0.html#the-future-is-here

**Comment by benesch** [comment]
Futures 0.2 was postponed and replaced by std::future::Future and async/await. I'm going to close this out for now. Once Rust 1.39 is released, we'll upgrade to be compatible with futures 0.3 and async/await (#143). For now, though, we'll stick with futures 0.1.
